#!/usr/bin/env python3
"""Derive the schema-unannotated.struct.json companions from the annotated samples.

Six real-world samples carry a second schema beside the annotated one, showing
the same feed without its semantic layer. The companion is produced from the
annotated schema by removing every keyword contributed by an extension add-in,
dropping the extension declarations, and dropping any definition that existed
only to give an annotation something to point at.

The companions are generated rather than hand-written so that they cannot drift
from the schemas they are meant to be compared against.

Usage:
    python make-unannotated.py            rewrite the companions
    python make-unannotated.py --check    fail if any companion is out of date
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent
META = ROOT.parent / "semantic-annotations-v0.json"

DIRECTORIES = [
    "09-orbit-mean-elements",
    "16-transit-vehicle-hfp",
    "17-usgs-instantaneous-value",
    "18-mode-s-aircraft-report",
    "19-bmrs-generation-mix",
    "20-goes-magnetometer",
]

# Keywords contributed by extension add-ins other than this one. The semantic
# annotation keywords are derived from the meta-schema below.
OTHER_EXTENSION_KEYWORDS = {"altenums", "altnames", "descriptions", "unit", "symbol"}

UNANNOTATED_SCHEMA = "https://json-structure.org/meta/extended/v0/#"
UNANNOTATED_USES = ["JSONStructureValidation"]

# The root description of an annotated sample ends with prose about the
# annotations themselves, which does not belong in a file that has none. These
# openers mark where that prose starts.
SAMPLE_PROSE_OPENERS = ("The sample exists because", "The sample demonstrates")

DERIVED_NOTE = (
    "This is the same record without its semantic layer, derived mechanically "
    "from `schema.struct.json` beside it: every keyword contributed by an "
    "extension add-in has been removed, along with any definition that existed "
    "only to give an annotation something to point at. What remains is the "
    "shape of the record and the prose a consumer would have to read to make "
    "sense of it. Read it against the annotated schema to see what the "
    "annotations carry. Do not edit this file; regenerate it with "
    "`make-unannotated.py`."
)


def annotation_keywords():
    """Every keyword the add-ins listed under $offers contribute."""
    meta = json.loads(META.read_text(encoding="utf-8"))
    keywords = set()
    for pointers in meta["$offers"].values():
        if isinstance(pointers, str):
            pointers = [pointers]
        for pointer in pointers:
            node = meta
            for part in pointer.lstrip("#/").split("/"):
                node = node[part]
            keywords.update(node.get("properties", {}))
    return keywords


def strip(node, keywords):
    if isinstance(node, dict):
        return {k: strip(v, keywords) for k, v in node.items() if k not in keywords}
    if isinstance(node, list):
        return [strip(v, keywords) for v in node]
    return node


def referenced(node, out):
    if isinstance(node, dict):
        target = node.get("$ref")
        if isinstance(target, str) and target.startswith("#/definitions/"):
            out.add(target.split("/")[2])
        for value in node.values():
            referenced(value, out)
    elif isinstance(node, list):
        for value in node:
            referenced(value, out)
    return out


def dump(obj, indent=0):
    """Serialise with scalar-only arrays inline, matching the sample house style."""
    pad = " " * indent
    if isinstance(obj, dict):
        if not obj:
            return "{}"
        items = [
            "%s  %s: %s" % (pad, json.dumps(k, ensure_ascii=False), dump(v, indent + 2))
            for k, v in obj.items()
        ]
        return "{\n" + ",\n".join(items) + "\n" + pad + "}"
    if isinstance(obj, list):
        if not obj:
            return "[]"
        if all(not isinstance(x, (dict, list)) for x in obj):
            return "[" + ", ".join(json.dumps(x, ensure_ascii=False) for x in obj) + "]"
        items = ["%s  %s" % (pad, dump(v, indent + 2)) for v in obj]
        return "[\n" + ",\n".join(items) + "\n" + pad + "]"
    return json.dumps(obj, ensure_ascii=False)


def derive(document, keywords):
    stripped = strip(document, keywords)
    stripped["$schema"] = UNANNOTATED_SCHEMA
    stripped["$id"] = document["$id"] + "-unannotated"
    stripped["$uses"] = list(UNANNOTATED_USES)

    description = stripped.get("description", "")
    cuts = [description.find(opener) for opener in SAMPLE_PROSE_OPENERS]
    cuts = [index for index in cuts if index > 0]
    if cuts:
        description = description[: min(cuts)]
    stripped["description"] = description.rstrip() + " " + DERIVED_NOTE

    dropped = []
    definitions = stripped.get("definitions")
    if isinstance(definitions, dict):
        live = referenced({k: v for k, v in stripped.items() if k != "definitions"}, set())
        changed = True
        while changed:
            changed = False
            for key in list(definitions):
                if key in live:
                    live |= referenced(definitions[key], set())
            for key in list(definitions):
                if key not in live:
                    dropped.append(key)
                    del definitions[key]
                    changed = True
        if not definitions:
            del stripped["definitions"]
    return stripped, dropped


def main(argv):
    check_only = "--check" in argv[1:]
    keywords = annotation_keywords() | OTHER_EXTENSION_KEYWORDS
    stale = []

    for name in DIRECTORIES:
        source = ROOT / "real-world" / name / "schema.struct.json"
        target = source.with_name("schema-unannotated.struct.json")
        document = json.loads(source.read_text(encoding="utf-8"))
        stripped, dropped = derive(document, keywords)
        text = dump(stripped) + "\n"

        if check_only:
            current = target.read_text(encoding="utf-8") if target.exists() else None
            if current != text:
                stale.append(name)
            continue

        target.write_text(text, encoding="utf-8")
        note = "dropped " + ", ".join(dropped) if dropped else ""
        print("%-30s %s" % (name, note))

    if check_only:
        if stale:
            print("out of date: " + ", ".join(stale))
            print("run make-unannotated.py to regenerate")
            return 1
        print("companions are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
